# Generated by Django 3.1.3 on 2022-01-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet_user',
            name='photos',
        ),
        migrations.AlterField(
            model_name='tweet_user',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
